### ISSUE TITLE
Restarting HA when away armed breaks something with keypad

### ISSUE THREAD

**Issue by schmuy** [ufodone/dscalarm#1]
When the system is away armed and Home Assistant is restarted there is a disconnect between panel and keypad.  Panel comes back away armed, but keypad reads arm stay.  This makes the physical system (DSC) keypad unresponsive.  There have been some cases where the service "Alarm control panel: Disarm" has not responded either.
<img width="1413" alt="Screenshot 2022-12-28 at 20 30 50" src="https://user-images.githubusercontent.com/93694290/210027606-2380695b-ebc7-4ff3-b177-d7147998c741.png">
![Image 2022-12-28 at 20 58](https://user-images.githubusercontent.com/93694290/210027608-e378727b-c39f-4f28-9845-b6c21cf2535d.jpg)

**Comment by ufodone** [comment]
@schmuy I believe I've fixed the issue with the keypad being unresponsive when HA is restarted while the alarm is armed.

I've published a new release (v0.2.0) which contains the fix.  In HACS, you may need to click on the `dscalarm` integration and then click the three dots in the upper right corner and do `Update Information` and then `Redownload` and install the v0.2.0 version.

I'm not sure about the discrepancy between of stay vs away between the keypad and panel.  Could you provide debug logging when this happens with the v0.2.0 version?

**Comment by schmuy** [comment]
The update showed for me under the updates section.  I applied the update from there and restarted.

I have not tested the keypad yet, but enabled the debug logs.  The behaviour with the difference in away arm/stay arm remained.

20:11:12 looks to be the moment the keypad sensor starts reading incorrectly.

Hope this helps

```
2022-12-31 19:51:03.638 INFO (MainThread) [custom_components.dscalarm] Start envisalink
2022-12-31 19:51:03.638 WARNING (MainThread) [root] Using a copy of the pyenvisalink package.
2022-12-31 19:51:03.727 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:51:04.153 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:51:04.155 INFO (MainThread) [custom_components.dscalarm] Established a connection with the Envisalink
2022-12-31 19:51:04.243 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:51:04.243 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:51:04.244 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.244 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.244 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.245 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.245 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.245 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.245 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.245 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.245 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.246 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.246 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.246 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.246 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.246 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.246 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.246 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.247 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.247 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.247 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.247 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.247 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.247 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:04.247 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.722 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.723 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.723 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.723 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.723 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.724 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.724 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.724 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.724 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.724 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.724 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.725 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.725 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.725 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.725 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.725 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.725 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.726 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.726 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.726 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.726 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.726 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.726 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.726 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.727 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.727 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.727 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.727 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.727 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.727 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.728 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.728 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.729 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.729 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.729 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.729 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.730 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.730 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.730 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.730 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.730 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:05.731 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:05.731 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:05.731 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:05.731 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:05.732 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:05.732 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:05.732 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:05.732 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:05.732 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:06.113 DEBUG (MainThread) [custom_components.dscalarm.alarm_control_panel] Setting up alarm: Home Alarm
2022-12-31 19:51:06.114 DEBUG (MainThread) [custom_components.dscalarm.sensor] Setting up sensor for partition: Home Alarm
2022-12-31 19:51:06.115 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Front Door
2022-12-31 19:51:06.115 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Garage In
2022-12-31 19:51:06.115 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Garage Out
2022-12-31 19:51:06.115 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Back Door
2022-12-31 19:51:06.115 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Living Room
2022-12-31 19:51:06.115 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Kitchen
2022-12-31 19:51:06.116 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Master Bed
2022-12-31 19:51:06.116 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Bed 1
2022-12-31 19:51:06.116 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Bed 2
2022-12-31 19:51:06.116 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Bed 3
2022-12-31 19:51:06.116 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Motion DS
2022-12-31 19:51:06.116 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Motion US
2022-12-31 19:51:06.117 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Front Door_bypass
2022-12-31 19:51:06.117 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Garage In_bypass
2022-12-31 19:51:06.117 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Garage Out_bypass
2022-12-31 19:51:06.117 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Back Door_bypass
2022-12-31 19:51:06.117 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Living Room_bypass
2022-12-31 19:51:06.117 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Kitchen_bypass
2022-12-31 19:51:06.117 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Master Bed_bypass
2022-12-31 19:51:06.118 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Bed 1_bypass
2022-12-31 19:51:06.118 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Bed 2_bypass
2022-12-31 19:51:06.118 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Bed 3_bypass
2022-12-31 19:51:06.118 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Motion DS_bypass
2022-12-31 19:51:06.118 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Motion US_bypass
2022-12-31 19:51:06.654 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:06.655 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:06.655 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:06.655 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:06.656 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:06.656 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:06.656 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:09.804 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:51:11.196 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:51:11.197 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone bypass update event. Updating zones
2022-12-31 19:51:36.396 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:51:36.397 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:48.272 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:51:49.207 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:52:03.673 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:52:06.129 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:52:06.134 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:52:36.130 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:52:36.134 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:52:47.738 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:52:49.545 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:53:03.675 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:53:06.132 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:53:06.135 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:53:25.195 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:53:27.005 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:53:36.134 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:53:36.137 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:54:03.675 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:54:05.803 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:54:06.135 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:54:06.138 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:54:07.609 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:54:36.135 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:54:36.139 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:55:03.677 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:55:06.136 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:55:06.140 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:55:36.138 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:55:36.142 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:56:03.678 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:56:06.140 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:56:06.143 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:56:36.140 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:56:36.144 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:56:38.616 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:56:40.426 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:57:03.680 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:57:06.142 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:57:06.145 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:57:36.143 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:57:36.149 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:57:52.387 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:01.669 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:02.058 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:03.681 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:58:05.772 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:06.144 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:58:06.147 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:06.396 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:13.586 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:31.467 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:31.626 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:58:33.197 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:33.355 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:58:36.145 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:58:36.151 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:40.487 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:40.644 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:58:41.031 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:41.188 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:58:55.643 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:55.801 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:58:56.909 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:58:57.067 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:59:02.313 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:59:02.471 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:59:03.682 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:59:06.146 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:59:06.149 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:59:36.175 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 19:59:36.178 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:59:49.256 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:59:49.415 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:59:51.074 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:59:51.231 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:59:55.007 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:59:55.165 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 19:59:56.817 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 19:59:56.975 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:00:03.707 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:00:06.177 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:00:06.180 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:00:36.178 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:00:36.182 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:01:03.708 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:01:06.181 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:01:06.186 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:01:36.183 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:01:36.191 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:02:03.709 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:02:06.185 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:02:06.189 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:02:36.187 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:02:36.191 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:03:03.714 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:03:06.188 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:03:06.192 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:03:36.189 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:03:36.193 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:03:41.972 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:03:42.128 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:03:43.787 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:03:43.945 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:04:03.715 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:04:06.190 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:04:06.194 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:04:36.191 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:04:36.198 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:04:53.792 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:04:53.950 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:04:55.600 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:04:55.758 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:05:03.717 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:05:06.192 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:05:06.196 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:16.015 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:16.172 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:05:17.833 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:17.991 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:05:18.693 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:18.857 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:05:20.503 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:20.661 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:05:21.682 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:21.839 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:05:28.864 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:29.025 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:05:36.172 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:36.207 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:05:36.252 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:36.330 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:05:42.191 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:42.349 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:05:57.039 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:57.198 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:05:58.849 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:59.007 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:05:59.475 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:05:59.633 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:06:01.208 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:06:01.405 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:06:03.719 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:06:06.209 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:06:06.213 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:06:10.495 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:06:10.654 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:06:12.229 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:06:12.387 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:06:36.210 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:06:36.213 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:07:03.720 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:07:06.211 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:07:06.216 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:07:07.184 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:07:07.341 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:07:08.995 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:07:09.153 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:07:36.219 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:07:36.221 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:07:41.313 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:07:42.142 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:08:03.722 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:08:06.214 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:08:06.217 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:08:36.215 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:08:36.220 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:08:41.844 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event






2022-12-31 20:11:06.145 INFO (MainThread) [custom_components.dscalarm] Start envisalink
2022-12-31 20:11:06.146 WARNING (MainThread) [root] Using a copy of the pyenvisalink package.
2022-12-31 20:11:06.743 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:11:06.777 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:11:06.779 INFO (MainThread) [custom_components.dscalarm] Established a connection with the Envisalink
2022-12-31 20:11:06.822 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:11:06.822 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:11:06.823 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.823 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.823 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.824 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.824 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.824 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.824 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.824 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.824 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.825 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.825 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.825 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.825 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.826 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.826 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.826 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.827 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.827 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.827 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.827 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.828 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.828 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:06.828 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.083 DEBUG (MainThread) [custom_components.dscalarm.alarm_control_panel] Setting up alarm: Home Alarm
2022-12-31 20:11:07.084 DEBUG (MainThread) [custom_components.dscalarm.sensor] Setting up sensor for partition: Home Alarm
2022-12-31 20:11:07.085 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Front Door
2022-12-31 20:11:07.085 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Garage In
2022-12-31 20:11:07.085 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Garage Out
2022-12-31 20:11:07.085 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Back Door
2022-12-31 20:11:07.085 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Living Room
2022-12-31 20:11:07.085 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Kitchen
2022-12-31 20:11:07.086 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Master Bed
2022-12-31 20:11:07.086 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Bed 1
2022-12-31 20:11:07.086 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Bed 2
2022-12-31 20:11:07.086 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Bed 3
2022-12-31 20:11:07.086 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Motion DS
2022-12-31 20:11:07.086 DEBUG (MainThread) [custom_components.dscalarm.binary_sensor] Setting up zone: Motion US
2022-12-31 20:11:07.087 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Front Door_bypass
2022-12-31 20:11:07.087 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Garage In_bypass
2022-12-31 20:11:07.087 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Garage Out_bypass
2022-12-31 20:11:07.087 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Back Door_bypass
2022-12-31 20:11:07.087 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Living Room_bypass
2022-12-31 20:11:07.087 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Kitchen_bypass
2022-12-31 20:11:07.087 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Master Bed_bypass
2022-12-31 20:11:07.088 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Bed 1_bypass
2022-12-31 20:11:07.088 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Bed 2_bypass
2022-12-31 20:11:07.088 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Bed 3_bypass
2022-12-31 20:11:07.088 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Motion DS_bypass
2022-12-31 20:11:07.088 DEBUG (MainThread) [custom_components.dscalarm.switch] Setting up zone_bypass switch: Motion US_bypass
2022-12-31 20:11:07.668 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.669 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.670 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.670 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.670 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.670 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.671 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.671 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.671 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.671 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.671 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.672 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.672 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.672 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.672 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.672 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.672 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.673 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.673 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.673 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.673 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.674 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.674 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:07.675 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.252 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.252 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.252 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.253 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.253 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.253 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.253 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.253 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.254 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.254 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.254 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.254 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.254 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.255 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.255 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.255 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.256 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:11:08.256 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:08.259 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:08.259 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:08.259 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:08.259 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:08.259 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:08.260 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:08.260 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:08.260 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:09.053 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:09.053 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:09.053 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:09.054 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:09.054 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:09.054 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:09.054 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:11.941 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:11:12.997 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:21.432 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.


2022-12-31 20:11:28.462 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:28.757 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:11:34.498 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:34.990 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:11:38.117 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:38.118 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:11:38.119 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones

2022-12-31 20:11:41.162 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:11:44.765 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:47.004 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:11:49.825 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:51.889 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.

2022-12-31 20:11:54.816 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:11:56.891 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.

2022-12-31 20:11:59.808 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:01.899 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:04.841 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:06.193 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:06.900 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:08.086 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:08.090 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:12:09.831 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:11.901 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:14.824 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:16.902 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:19.816 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:21.903 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:24.806 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:26.905 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:29.801 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:31.927 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:34.831 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:36.931 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:38.088 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:38.091 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:12:39.813 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:41.931 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:44.807 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:45.923 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:47.138 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:47.322 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:50.798 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:51.934 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:12:53.478 DEBUG (MainThread) [custom_components.dscalarm] The envisalink sent a partition update event
2022-12-31 20:12:53.481 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone bypass update event. Updating zones
2022-12-31 20:13:06.188 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:13:08.089 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:13:08.093 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:13:38.090 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:13:38.094 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:14:06.189 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:14:08.092 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:14:08.096 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
2022-12-31 20:14:38.094 DEBUG (MainThread) [custom_components.dscalarm.pyenvisalink.alarm_panel] Callback has not been set by client.
2022-12-31 20:14:38.097 DEBUG (MainThread) [custom_components.dscalarm] Envisalink sent a zone update event. Updating zones
```

<img width="1444" alt="Screenshot 2022-12-31 at 20 31 34" src="https://user-images.githubusercontent.com/93694290/210161060-c37d60ef-3c19-4b51-9beb-a7bed9393232.png">

**Comment by ufodone** [comment]
It looks like I messed up the changes a bit so the 0.2.0 release wouldn't have fixed the keypad lockup issue.  I've pushed a new version now which should fix that (0.2.1).

I tried reproducing the armed home/away issue but it appeared to work fine on my system.  Could you retest with the latest release and re-send the logs?  The last logs didn't include the debug info I needed because of the bug I fixed in 0.2.1.  Please make sure you have in your configuration.yaml something like:

```
logger:
  default: info
  logs:
    custom_components.dscalarm: debug
```

And please also note that the logs may contain your EVL password and alarm code with debug logging on so be careful to either scrub them out of the logs or change them temporarily to something different.

Thanks!

**Comment by schmuy** [comment]
I have not had a chance to go through logs, but as of a restart a couple min ago keypad and panel are reporting same state.  I can still get logs for you if you like, but on the surface it looks like it's been resolved.  Thanks for working on this so quickly.

**Comment by ufodone** [comment]
No need for logs if everything is working for you now.  It's possible that the issue with the physical keypad getting stuck may have been causing the panel/keypad states to be out of sync.
